export const userData = { 
    first_name: "Peter",
    middle_name: "",
    last_name: "Petrosvki",
    status: "Not Qualified",
    worklist: "",
    recruiter: "",
    processor: ""
}



export const user = {
    "_id": "642de770cbc88136c7886f1c",
    "user_type": "User",
    "is_application_completed": true,
    "first_name": "Anmol",
    "middle_name": "Kumar",
    "last_name": "Gupta",
    "suffix": "Sr.",
    "ssn": "123456789",
    "dob": "1999-02-02T00:00:00.000Z",
    "gender": "Male",
    "current_street_address_line1": "1331 Atwater",
    "current_street_address_line2": "IU Area",
    "country": "US",
    "city": "Btown",
    "state_province": "IN",
    "zip_code": "47401",
    "residence_address_for_3_years_or_more": false,
    "primary_phone": "123467890",
    "cell_phone": "123457890",
    "email": "andy22@gmail.com",
    "confirm_email": "andy22@gmail.com",
    "receive_communication_via_email": true,
    "receive_communication_via_text": true,
    "user_license_details_id": [
        {
            "_id": "642dea43cbc88136c7886f28",
            "license_number": "123456789",
            "country": "USA",
            "state_licensing_authority": "Indiana",
            "license_expiration": "1999-02-02T00:00:00.000Z",
            "physical_expiration": "1999-02-02T00:00:00.000Z",
            "current_license": true,
            "commercial_license": true,
            "license_class": "Class A",
            "endorsements": "None",
            "__v": 0
        }
    ],
    "createdAt": "2023-04-05T21:26:08.429Z",
    "updatedAt": "2023-04-06T00:47:21.820Z",
    "__v": 1,
    "user_general_information_id": {
        "_id": "642de953cbc88136c7886f21",
        "position_applied": "Owner Operator",
        "if_applied_as_owner_operator_or_fleet_owner": true,
        "legally_eligible_for_employment_in_US": true,
        "currently_employed": true,
        "last_date_of_employment": "2023-04-05T00:00:00.000Z",
        "read_write_speak_english": true,
        "previously_employed_by_same_company": true,
        "info_about_employment_by_same_company": "some random info",
        "current_TWIC_card": true,
        "twic_card_expiration": "2025-02-02T00:00:00.000Z",
        "known_other_names": true,
        "other_name": "Kush",
        "how_do_you_hear_about_us": "Driver Referral",
        "if_driver_referral_enter_drivers_name": "Some driver",
        "equipment_details_owner_and_operators_id": {
            "_id": "642de952cbc88136c7886f1f",
            "type": "Some Type",
            "year_made": "1999",
            "make": "Some Make",
            "model": "Some Model",
            "color": "Some Color",
            "vin": "Some VIN",
            "weight": "Some Weight",
            "mileage": "Some Mileage",
            "fifth_wheel_height": "Some Height",
            "__v": 0
        },
        "createdAt": "2023-04-05T21:34:11.024Z",
        "updatedAt": "2023-04-05T21:34:11.024Z",
        "__v": 0
    },
    "user_driving_experience": {
        "_id": "642dea1dcbc88136c7886f24",
        "straight_truck": "1-2 years",
        "tractor_and_semi_trailers": "1-2 years",
        "tractor_two_trailers": "1-2 years",
        "createdAt": "2023-04-05T21:37:33.209Z",
        "updatedAt": "2023-04-05T21:37:33.209Z",
        "__v": 0
    },
    "in_military": true,
    "user_military_info_id": {
        "_id": "642deb47cbc88136c7886f2d",
        "branch_of_service": "Army",
        "start_date": "2018-02-02T00:00:00.000Z",
        "end_date": "2019-02-02T00:00:00.000Z",
        "rank_at_discharge": "major",
        "can_obtain_DD214": true,
        "__v": 0
    },
    "user_work_school_conviction_violation_unemployment_history_id": {
        "_id": "642decf88eed261f3f9b2ae1",
        "employed_contracted_attended_company_orientation_last_3years": true,
        "user_employer_information_id": [
            {
                "_id": "642decf88eed261f3f9b2ae2",
                "company_name": "Some company",
                "start_date": "1999-02-02T00:00:00.000Z",
                "end_date": "1999-02-02T00:00:00.000Z",
                "street_address_1": "add",
                "street_address_2": "add",
                "country": "USA",
                "city": "Bloomington",
                "state": "Indiana",
                "postal_code": "47401",
                "telephone": "1234567890",
                "position_held": "position",
                "reason_for_leaving": "reason",
                "explanation_for_termination": "explanation",
                "is_this_current_employer": true,
                "can_we_contact_this_employer": true,
                "operated_commercial_motor_vehicle": true,
                "subject_to_fmcsa_or_transport_canada": true,
                "areas_driven": "areas",
                "miles_driven_weekly": "0 - 500 Miles",
                "pay_range_cents_per_mile": "10",
                "most_common_truck_driven": "Tanker",
                "most_common_trailer": "Flatbed",
                "trailer_length": "31 feet or less",
                "createdAt": "2023-04-05T21:49:44.116Z",
                "updatedAt": "2023-04-05T21:49:44.116Z",
                "__v": 0
            },
            {
                "_id": "642e0128087df20621bd5454",
                "company_name": "Some company 1",
                "start_date": "1999-02-02T00:00:00.000Z",
                "end_date": "1999-02-02T00:00:00.000Z",
                "street_address_1": "add",
                "street_address_2": "add",
                "country": "USA",
                "city": "Bloomington",
                "state": "Indiana",
                "postal_code": "47401",
                "telephone": "1234567890",
                "position_held": "position",
                "reason_for_leaving": "reason",
                "explanation_for_termination": "explanation",
                "is_this_current_employer": true,
                "can_we_contact_this_employer": true,
                "operated_commercial_motor_vehicle": true,
                "subject_to_fmcsa_or_transport_canada": true,
                "areas_driven": "areas",
                "miles_driven_weekly": "0 - 500 Miles",
                "pay_range_cents_per_mile": "10",
                "most_common_truck_driven": "Tanker",
                "most_common_trailer": "Flatbed",
                "trailer_length": "31 feet or less",
                "createdAt": "2023-04-05T23:15:52.280Z",
                "updatedAt": "2023-04-05T23:15:52.280Z",
                "__v": 0
            }
        ],
        "driving_schools_attended": [
            {
                "_id": "642e01e358e1bdf4b3d87ce0",
                "is_driving_school": true,
                "school_name": "school",
                "start_date": "1999-02-02T00:00:00.000Z",
                "end_date": "2000-02-02T00:00:00.000Z",
                "street_address_1": "addy",
                "street_address_2": "addy",
                "country": "USA",
                "city": "City",
                "state": "Indiana",
                "postal_code": "47401",
                "telephone": "123456789",
                "did_you_graduate": true,
                "subject_to_fmcsa_or_transport_canada": true,
                "perform_safety_sensitive_functions_regulated_by_DOT_and_subject_drug_alcohol_testing": true,
                "gpa": "10",
                "hours_of_instruction": "10 or more",
                "skills_trained": "Border Crossing",
                "graduation_date": "2010-02-02T00:00:00.000Z",
                "major": "major",
                "__v": 0
            },
            {
                "_id": "642e020058e1bdf4b3d87ce5",
                "is_driving_school": true,
                "school_name": "school 1",
                "start_date": "1999-02-02T00:00:00.000Z",
                "end_date": "2000-02-02T00:00:00.000Z",
                "street_address_1": "addy",
                "street_address_2": "addy",
                "country": "USA",
                "city": "City",
                "state": "Indiana",
                "postal_code": "47401",
                "telephone": "123456789",
                "did_you_graduate": true,
                "subject_to_fmcsa_or_transport_canada": true,
                "perform_safety_sensitive_functions_regulated_by_DOT_and_subject_drug_alcohol_testing": true,
                "gpa": "10",
                "hours_of_instruction": "10 or more",
                "skills_trained": "Border Crossing",
                "graduation_date": "2010-02-02T00:00:00.000Z",
                "major": "major",
                "__v": 0
            }
        ],
        "schools_attended": [
            "642e02b558e1bdf4b3d87cea"
        ],
        "user_unemployment_details": [
            {
                "_id": "642e035f58e1bdf4b3d87cef",
                "start_date": "2011-02-02T00:00:00.000Z",
                "end_date": "2011-02-02T00:00:00.000Z",
                "comments": "comments",
                "__v": 0
            }
        ],
        "moving_violations_traffic_convictions_last_3Years_details": [
            {
                "_id": "642e148858e1bdf4b3d87cf8",
                "violation_date": "2011-02-02T00:00:00.000Z",
                "charge_description": "Careless Reckless Driving",
                "state": "IN",
                "were_you_in_commercial_vechicle": true,
                "penalty_fine": "Fine",
                "fine_amount": "$0 - $99",
                "comments": "comments",
                "__v": 0
            },
            {
                "_id": "642e14af58e1bdf4b3d87cfd",
                "violation_date": "2011-02-02T00:00:00.000Z",
                "charge_description": "Seatbelt",
                "state": "state",
                "were_you_in_commercial_vechicle": true,
                "penalty_fine": "Fine",
                "fine_amount": "$0 - $99",
                "comments": "comments",
                "__v": 0
            }
        ],
        "accidents_with_any_vechicle_in_last_5years_details": [
            {
                "_id": "642e14d758e1bdf4b3d87d02",
                "accident_date": "2011-02-02T00:00:00.000Z",
                "accident_type": "Injury",
                "hazmat_accident": true,
                "vechicle_towed": true,
                "city": "city",
                "state": "state",
                "were_you_in_commercial_vechicle": true,
                "DOT_recordable_incident": true,
                "were_you_at_fault": true,
                "ever_ticketed": true,
                "more_details": "more_details",
                "__v": 0
            }
        ],
        "__v": 8,
        "attended_driving_school": true,
        "any_criminal_charges_pending": true,
        "any_deferred_prosecution": true,
        "crime_conviction_details": "details",
        "deferred_prosecution_details": "details",
        "ever_convicted_of_crime": true,
        "ever_pled_guilty_or_convicted_or_no_contest_to_felony": true,
        "guilty_conviction_no_contest_felony_details": "details",
        "if_convicted_does_hold_ministers_permit_to_enter_exit_canada": true,
        "ministers_permit_to_enter_exit_canada_details": "details",
        "pending_criminal_charges_pending": "details",
        "pled_guilty_or_convicted_or_no_contest_to_misdemeanors": true,
        "pled_guilty_or_convicted_or_no_contest_to_misdemeanors_details": "details"
    },
    "user_FMCSR_details_id": {
        "_id": "642e055958e1bdf4b3d87cf3",
        "currently_disqualified_driving_commercial_motor_vehicle": true,
        "additional_details_on_49_CFR_391_15": "details",
        "license_permit_privilege_ever_suspended_revoked": true,
        "additional_details_on_suspension": "details",
        "denied_license_permit_privilege_operate_motor_vehicle": true,
        "additional_details_on_denial_of_license_permit_privileges": "details",
        "tested_positive_for_drug_or_alcohol": true,
        "details_on_tested_positive_for_drug_or_alcohol": "details",
        "last_date_of_positive_or_refusal": "2011-02-02T00:00:00.000Z",
        "in_past_3years_convicted_of_offences_49_cfr_391_15_and_49cfr3952": true,
        "three_years_before_convicted_for_same_or_other_offenses": true,
        "most_recent_conviction_identified_date": "2011-02-02T00:00:00.000Z",
        "additional_details_on_each_conviction": "details",
        "__v": 0
    },
    "user_rights_info_id": {
        "_id": "642e169958e1bdf4b3d87d09",
        "fcra_summary_of_rights": true,
        "psp_disclosure_and_authorization": true,
        "diclousure_for_consumer_reports": true,
        "authorization_for_consumer_reports": true,
        "disclousure_and_auth_cfrpart391_23_DOT_drug_alcohol_info": true,
        "summary_of_rights_Under_15usc_section_1681": true,
        "investigative_comsumer_report_disclosure": true,
        "final_signature": true,
        "__v": 0
    }
}



export default user;
